server:
  port: 8761

eureka:
  client:
    servieUrl:
      defaultZone: http://127.0.0.1:8011/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
